name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

  pull_request:
    branches:
      - npne
    paths:
      - 'backend/**'
  

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Virtual Environment
        run: |
          python -m venv venv

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django Check
        run: |
          source venv/bin/activate
          python manage.py check

      - name: Collect Static Files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Upload Backend
        uses: actions/upload-artifact@v4
        with:
          name: django-backend
          path: backend